name = "pluma-proto"
version = "0.1.0"
defaultTargets = ["PlumaProto"]

[[require]]
name = "leansqlite"
git = "https://github.com/leanprover/leansqlite.git"
rev = "v4.30.0"

[[lean_lib]]
name = "PlumaProto"
